// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// 设备信息数据类。对照 L1 手写时靠 Map{'model': ..., 'systemVersion': ...} 手拼手拆，
/// 这里声明成"字段强类型的类"，Pigeon 生成三端等价的类 + 编解码。
/// 字段非空 → 三端生成的都是非空类型，少传一个字段编译期就报（手写 Map 做不到）。
class DeviceInfoData {
  DeviceInfoData({
    required this.model,
    required this.systemName,
    required this.systemVersion,
    required this.isPhysicalDevice,
    this.batteryLevel,
  });

  String model;

  String systemName;

  String systemVersion;

  bool isPhysicalDevice;

  int? batteryLevel;

  List<Object?> _toList() {
    return <Object?>[
      model,
      systemName,
      systemVersion,
      isPhysicalDevice,
      batteryLevel,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeviceInfoData decode(Object result) {
    result as List<Object?>;
    return DeviceInfoData(
      model: result[0]! as String,
      systemName: result[1]! as String,
      systemVersion: result[2]! as String,
      isPhysicalDevice: result[3]! as bool,
      batteryLevel: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeviceInfoData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(model, other.model) && _deepEquals(systemName, other.systemName) && _deepEquals(systemVersion, other.systemVersion) && _deepEquals(isPhysicalDevice, other.isPhysicalDevice) && _deepEquals(batteryLevel, other.batteryLevel);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DeviceInfoData(model: $model, systemName: $systemName, systemVersion: $systemVersion, isPhysicalDevice: $isPhysicalDevice, batteryLevel: $batteryLevel)';
  }
}

/// 电量信息。反向推流（FlutterApi）用的强类型载荷——对照 L3 EventChannel 推 Map 要手拆。
class BatteryInfo {
  BatteryInfo({
    required this.level,
    required this.isCharging,
  });

  int level;

  bool isCharging;

  List<Object?> _toList() {
    return <Object?>[
      level,
      isCharging,
    ];
  }

  Object encode() {
    return _toList();  }

  static BatteryInfo decode(Object result) {
    result as List<Object?>;
    return BatteryInfo(
      level: result[0]! as int,
      isCharging: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BatteryInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(level, other.level) && _deepEquals(isCharging, other.isCharging);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BatteryInfo(level: $level, isCharging: $isCharging)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is DeviceInfoData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is BatteryInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return DeviceInfoData.decode(readValue(buffer)!);
      case 130:
        return BatteryInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// @HostApi：Flutter → 原生（对照 L1 的"Dart 调原生"）。
/// 这些方法名就是契约——生成后 Dart 侧 host.getDeviceInfo() 是真方法，
/// 改名/改签名两端一起编译报错（对照手写：invokeMethod('getDeviceInfo') 打错字运行期才崩）。
class DeviceInfoHostApi {
  /// Constructor for [DeviceInfoHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DeviceInfoHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// @async：原生实现端拿到一个 completion/callback，可异步完成（演示 Pigeon 的异步契约）。
  Future<DeviceInfoData> getDeviceInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.native_lab.DeviceInfoHostApi.getDeviceInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as DeviceInfoData;
  }

  Future<BatteryInfo> getBatteryInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.native_lab.DeviceInfoHostApi.getBatteryInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BatteryInfo;
  }

  /// 开始/停止电量订阅——对照 L3 EventChannel 的 onListen/onCancel，
  /// 但这里是普通方法调用，真正的推流走下面的 FlutterApi。
  Future<void> startBatteryUpdates() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.native_lab.DeviceInfoHostApi.startBatteryUpdates$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopBatteryUpdates() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.native_lab.DeviceInfoHostApi.stopBatteryUpdates$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// @FlutterApi：原生 → Flutter（反向）。生成后原生侧持有一个
/// DeviceEventFlutterApi 实例，调 onBatteryChanged(info) 就把强类型对象推给 Dart。
/// 这是 L3 EventChannel 的"类型安全版"：L3 事件是裸 Map 要手拆，这里是生成的 BatteryInfo。
abstract class DeviceEventFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onBatteryChanged(BatteryInfo info);

  static void setUp(DeviceEventFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.native_lab.DeviceEventFlutterApi.onBatteryChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final BatteryInfo arg_info = args[0]! as BatteryInfo;
          try {
            api.onBatteryChanged(arg_info);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
