// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.wenbo.native_lab

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object DeviceInfoMessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * 设备信息数据类。对照 L1 手写时靠 Map{'model': ..., 'systemVersion': ...} 手拼手拆，
 * 这里声明成"字段强类型的类"，Pigeon 生成三端等价的类 + 编解码。
 * 字段非空 → 三端生成的都是非空类型，少传一个字段编译期就报（手写 Map 做不到）。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceInfoData (
  val model: String,
  val systemName: String,
  val systemVersion: String,
  val isPhysicalDevice: Boolean,
  val batteryLevel: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceInfoData {
      val model = pigeonVar_list[0] as String
      val systemName = pigeonVar_list[1] as String
      val systemVersion = pigeonVar_list[2] as String
      val isPhysicalDevice = pigeonVar_list[3] as Boolean
      val batteryLevel = pigeonVar_list[4] as Long?
      return DeviceInfoData(model, systemName, systemVersion, isPhysicalDevice, batteryLevel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      model,
      systemName,
      systemVersion,
      isPhysicalDevice,
      batteryLevel,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DeviceInfoData
    return DeviceInfoMessagesPigeonUtils.deepEquals(this.model, other.model) && DeviceInfoMessagesPigeonUtils.deepEquals(this.systemName, other.systemName) && DeviceInfoMessagesPigeonUtils.deepEquals(this.systemVersion, other.systemVersion) && DeviceInfoMessagesPigeonUtils.deepEquals(this.isPhysicalDevice, other.isPhysicalDevice) && DeviceInfoMessagesPigeonUtils.deepEquals(this.batteryLevel, other.batteryLevel)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DeviceInfoMessagesPigeonUtils.deepHash(this.model)
    result = 31 * result + DeviceInfoMessagesPigeonUtils.deepHash(this.systemName)
    result = 31 * result + DeviceInfoMessagesPigeonUtils.deepHash(this.systemVersion)
    result = 31 * result + DeviceInfoMessagesPigeonUtils.deepHash(this.isPhysicalDevice)
    result = 31 * result + DeviceInfoMessagesPigeonUtils.deepHash(this.batteryLevel)
    return result
  }
  override fun toString(): String {
    return "DeviceInfoData(model=$model, systemName=$systemName, systemVersion=$systemVersion, isPhysicalDevice=$isPhysicalDevice, batteryLevel=$batteryLevel)"
  }
}

/**
 * 电量信息。反向推流（FlutterApi）用的强类型载荷——对照 L3 EventChannel 推 Map 要手拆。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BatteryInfo (
  val level: Long,
  val isCharging: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BatteryInfo {
      val level = pigeonVar_list[0] as Long
      val isCharging = pigeonVar_list[1] as Boolean
      return BatteryInfo(level, isCharging)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      level,
      isCharging,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BatteryInfo
    return DeviceInfoMessagesPigeonUtils.deepEquals(this.level, other.level) && DeviceInfoMessagesPigeonUtils.deepEquals(this.isCharging, other.isCharging)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DeviceInfoMessagesPigeonUtils.deepHash(this.level)
    result = 31 * result + DeviceInfoMessagesPigeonUtils.deepHash(this.isCharging)
    return result
  }
  override fun toString(): String {
    return "BatteryInfo(level=$level, isCharging=$isCharging)"
  }
}
private open class DeviceInfoMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceInfoData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BatteryInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DeviceInfoData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BatteryInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * @HostApi：Flutter → 原生（对照 L1 的"Dart 调原生"）。
 * 这些方法名就是契约——生成后 Dart 侧 host.getDeviceInfo() 是真方法，
 * 改名/改签名两端一起编译报错（对照手写：invokeMethod('getDeviceInfo') 打错字运行期才崩）。
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DeviceInfoHostApi {
  /** @async：原生实现端拿到一个 completion/callback，可异步完成（演示 Pigeon 的异步契约）。 */
  fun getDeviceInfo(callback: (Result<DeviceInfoData>) -> Unit)
  /**
   * 开始/停止电量订阅——对照 L3 EventChannel 的 onListen/onCancel，
   * 但这里是普通方法调用，真正的推流走下面的 FlutterApi。
   */
  fun startBatteryUpdates()
  fun stopBatteryUpdates()

  companion object {
    /** The codec used by DeviceInfoHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      DeviceInfoMessagesPigeonCodec()
    }
    /** Sets up an instance of `DeviceInfoHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DeviceInfoHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_lab.DeviceInfoHostApi.getDeviceInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeviceInfo{ result: Result<DeviceInfoData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DeviceInfoMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(DeviceInfoMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_lab.DeviceInfoHostApi.startBatteryUpdates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startBatteryUpdates()
              listOf(null)
            } catch (exception: Throwable) {
              DeviceInfoMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_lab.DeviceInfoHostApi.stopBatteryUpdates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopBatteryUpdates()
              listOf(null)
            } catch (exception: Throwable) {
              DeviceInfoMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * @FlutterApi：原生 → Flutter（反向）。生成后原生侧持有一个
 * DeviceEventFlutterApi 实例，调 onBatteryChanged(info) 就把强类型对象推给 Dart。
 * 这是 L3 EventChannel 的"类型安全版"：L3 事件是裸 Map 要手拆，这里是生成的 BatteryInfo。
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class DeviceEventFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DeviceEventFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      DeviceInfoMessagesPigeonCodec()
    }
  }
  fun onBatteryChanged(infoArg: BatteryInfo, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.native_lab.DeviceEventFlutterApi.onBatteryChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(infoArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DeviceInfoMessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
