// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum DeviceInfoMessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// 设备信息数据类。对照 L1 手写时靠 Map{'model': ..., 'systemVersion': ...} 手拼手拆，
/// 这里声明成"字段强类型的类"，Pigeon 生成三端等价的类 + 编解码。
/// 字段非空 → 三端生成的都是非空类型，少传一个字段编译期就报（手写 Map 做不到）。
///
/// Generated class from Pigeon that represents data sent in messages.
struct DeviceInfoData: Hashable, CustomStringConvertible {
  var model: String
  var systemName: String
  var systemVersion: String
  var isPhysicalDevice: Bool
  var batteryLevel: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceInfoData? {
    let model = pigeonVar_list[0] as! String
    let systemName = pigeonVar_list[1] as! String
    let systemVersion = pigeonVar_list[2] as! String
    let isPhysicalDevice = pigeonVar_list[3] as! Bool
    let batteryLevel: Int64? = nilOrValue(pigeonVar_list[4])

    return DeviceInfoData(
      model: model,
      systemName: systemName,
      systemVersion: systemVersion,
      isPhysicalDevice: isPhysicalDevice,
      batteryLevel: batteryLevel
    )
  }
  func toList() -> [Any?] {
    return [
      model,
      systemName,
      systemVersion,
      isPhysicalDevice,
      batteryLevel,
    ]
  }
  static func == (lhs: DeviceInfoData, rhs: DeviceInfoData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DeviceInfoMessagesPigeonInternal.deepEquals(lhs.model, rhs.model) && DeviceInfoMessagesPigeonInternal.deepEquals(lhs.systemName, rhs.systemName) && DeviceInfoMessagesPigeonInternal.deepEquals(lhs.systemVersion, rhs.systemVersion) && DeviceInfoMessagesPigeonInternal.deepEquals(lhs.isPhysicalDevice, rhs.isPhysicalDevice) && DeviceInfoMessagesPigeonInternal.deepEquals(lhs.batteryLevel, rhs.batteryLevel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DeviceInfoData")
    DeviceInfoMessagesPigeonInternal.deepHash(value: model, hasher: &hasher)
    DeviceInfoMessagesPigeonInternal.deepHash(value: systemName, hasher: &hasher)
    DeviceInfoMessagesPigeonInternal.deepHash(value: systemVersion, hasher: &hasher)
    DeviceInfoMessagesPigeonInternal.deepHash(value: isPhysicalDevice, hasher: &hasher)
    DeviceInfoMessagesPigeonInternal.deepHash(value: batteryLevel, hasher: &hasher)
  }

  public var description: String {
    return "DeviceInfoData(model: \(String(describing: model)), systemName: \(String(describing: systemName)), systemVersion: \(String(describing: systemVersion)), isPhysicalDevice: \(String(describing: isPhysicalDevice)), batteryLevel: \(String(describing: batteryLevel)))"
  }
}

/// 电量信息。反向推流（FlutterApi）用的强类型载荷——对照 L3 EventChannel 推 Map 要手拆。
///
/// Generated class from Pigeon that represents data sent in messages.
struct BatteryInfo: Hashable, CustomStringConvertible {
  var level: Int64
  var isCharging: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BatteryInfo? {
    let level = pigeonVar_list[0] as! Int64
    let isCharging = pigeonVar_list[1] as! Bool

    return BatteryInfo(
      level: level,
      isCharging: isCharging
    )
  }
  func toList() -> [Any?] {
    return [
      level,
      isCharging,
    ]
  }
  static func == (lhs: BatteryInfo, rhs: BatteryInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DeviceInfoMessagesPigeonInternal.deepEquals(lhs.level, rhs.level) && DeviceInfoMessagesPigeonInternal.deepEquals(lhs.isCharging, rhs.isCharging)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BatteryInfo")
    DeviceInfoMessagesPigeonInternal.deepHash(value: level, hasher: &hasher)
    DeviceInfoMessagesPigeonInternal.deepHash(value: isCharging, hasher: &hasher)
  }

  public var description: String {
    return "BatteryInfo(level: \(String(describing: level)), isCharging: \(String(describing: isCharging)))"
  }
}

private class DeviceInfoMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return DeviceInfoData.fromList(self.readValue() as! [Any?])
    case 130:
      return BatteryInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DeviceInfoMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DeviceInfoData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? BatteryInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DeviceInfoMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DeviceInfoMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DeviceInfoMessagesPigeonCodecWriter(data: data)
  }
}

class DeviceInfoMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DeviceInfoMessagesPigeonCodec(readerWriter: DeviceInfoMessagesPigeonCodecReaderWriter())
}


/// @HostApi：Flutter → 原生（对照 L1 的"Dart 调原生"）。
/// 这些方法名就是契约——生成后 Dart 侧 host.getDeviceInfo() 是真方法，
/// 改名/改签名两端一起编译报错（对照手写：invokeMethod('getDeviceInfo') 打错字运行期才崩）。
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DeviceInfoHostApi {
  /// @async：原生实现端拿到一个 completion/callback，可异步完成（演示 Pigeon 的异步契约）。
  func getDeviceInfo(completion: @escaping (Result<DeviceInfoData, Error>) -> Void)
  func getBatteryInfo(completion: @escaping (Result<BatteryInfo, Error>) -> Void)
  /// 开始/停止电量订阅——对照 L3 EventChannel 的 onListen/onCancel，
  /// 但这里是普通方法调用，真正的推流走下面的 FlutterApi。
  func startBatteryUpdates() throws
  func stopBatteryUpdates() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DeviceInfoHostApiSetup {
  static var codec: FlutterStandardMessageCodec { DeviceInfoMessagesPigeonCodec.shared }
  /// Sets up an instance of `DeviceInfoHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DeviceInfoHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// @async：原生实现端拿到一个 completion/callback，可异步完成（演示 Pigeon 的异步契约）。
    let getDeviceInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_lab.DeviceInfoHostApi.getDeviceInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceInfoChannel.setMessageHandler { _, reply in
        api.getDeviceInfo { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDeviceInfoChannel.setMessageHandler(nil)
    }
    let getBatteryInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_lab.DeviceInfoHostApi.getBatteryInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBatteryInfoChannel.setMessageHandler { _, reply in
        api.getBatteryInfo { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBatteryInfoChannel.setMessageHandler(nil)
    }
    /// 开始/停止电量订阅——对照 L3 EventChannel 的 onListen/onCancel，
    /// 但这里是普通方法调用，真正的推流走下面的 FlutterApi。
    let startBatteryUpdatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_lab.DeviceInfoHostApi.startBatteryUpdates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startBatteryUpdatesChannel.setMessageHandler { _, reply in
        do {
          try api.startBatteryUpdates()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startBatteryUpdatesChannel.setMessageHandler(nil)
    }
    let stopBatteryUpdatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_lab.DeviceInfoHostApi.stopBatteryUpdates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopBatteryUpdatesChannel.setMessageHandler { _, reply in
        do {
          try api.stopBatteryUpdates()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopBatteryUpdatesChannel.setMessageHandler(nil)
    }
  }
}

/// @FlutterApi：原生 → Flutter（反向）。生成后原生侧持有一个
/// DeviceEventFlutterApi 实例，调 onBatteryChanged(info) 就把强类型对象推给 Dart。
/// 这是 L3 EventChannel 的"类型安全版"：L3 事件是裸 Map 要手拆，这里是生成的 BatteryInfo。
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DeviceEventFlutterApiProtocol {
  func onBatteryChanged(info infoArg: BatteryInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class DeviceEventFlutterApi: DeviceEventFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: DeviceInfoMessagesPigeonCodec {
    return DeviceInfoMessagesPigeonCodec.shared
  }
  func onBatteryChanged(info infoArg: BatteryInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.native_lab.DeviceEventFlutterApi.onBatteryChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([infoArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
